### Manual tests for REST Client VS Code Extension
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@localBasePath=http://localhost:7071/
@afBasePath=https://myserverlessreqbin.azurewebsites.net/

@basePath={{afBasePath}}

GET {{basePath}}12345?a=1&b=2
x-my-header:1234567890                

###
POST {{basePath}}12345
x-my-header:1234567890

<xml>Hello from VS CODE!</xml>
1 
  2
    3
      4
        5
          6
            7
              8
                9

###
PUT {{basePath}}12345?a=1&b=2
x-my-header:1234567890

<xml>Hello from VS CODE!</xml>
1 
  2
    3
      4
        5
          6
            7
              8
                9

###
PATCH {{basePath}}12345?a=1&b=2
x-my-header:1234567890

<xml>Hello from VS CODE!</xml>
1 
  2
    3
      4
        5
          6
            7
              8
                9

###
HEAD {{basePath}}12345?a=1&b=2

###
OPTIONS {{basePath}}12345?a=1&b=2

###
TRACE {{basePath}}12345?a=1&b=2

###
GET {{basePath}}history/12345

###
DELETE {{basePath}}history/12345
