### Manual tests for REST Client VS Code Extension
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@localBasePath=http://localhost:7071/
@afBasePath=https://myserverlessreqbin.azurewebsites.net/

@basePath={{afBasePath}}

GET {{basePath}}12345?a=1&b=2&c=my%20value&d=%21%40%23%24%25%5E%26%2A%28%29
x-my-header:1234567890               
x-my-other-header:abcdefg             

###
POST {{basePath}}12345
x-my-header:1234567890             
x-my-other-header:abcdefg         

<xml>Hello from VS CODE! @ API Days</xml>


###
PUT {{basePath}}12345?a=1&b=2
x-my-header:1234567890             
x-my-other-header:zxcvbnm         

<xml>
  <item>Hello from VS CODE! @ API Days</item>
  <item>Hello from VS CODE! @ API Days</item>
  <item>Hello from VS CODE! @ API Days</item>
  <item>Hello from VS CODE! @ API Days</item>
  <item>Hello from VS CODE! @ API Days</item>
</xml>


###
PATCH {{basePath}}12345?a=1&b=2
x-my-header:1234567890       
x-my-other-header:zxcvbnm         

<xml>
  <item>Hello from VS CODE! @ API Days</item>
  <item>Hello from VS CODE! @ API Days</item>
</xml>


###
HEAD {{basePath}}12345?a=1&b=2
x-my-header:12345   
x-my-other-header:09876    

###
OPTIONS {{basePath}}12345?a=1&b=2
x-my-header:12345   
x-my-other-header:09876    

###
TRACE {{basePath}}12345?a=1&b=2
x-my-header:12345   
x-my-other-header:09876    

###
GET {{basePath}}history/12345

###
DELETE {{basePath}}history/12345
